Automation: fix build on el9
Fixes:
```
Error: It wasn't possible to enable this project.
Repository 'epel-9-x86_64' does not exist in project 'ovirt/ovirt-master-snapshot'.
```

Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>